/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.univalle.examenfinalfpoe.view;

import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.JTextField;

/**
 *
 * @author Sebastián
 */
public class principalView extends javax.swing.JFrame {

    /**
     * Creates new form principalView
     */
    public principalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jContenido = new javax.swing.JPanel();
        jDatos = new javax.swing.JPanel();
        jLabelId = new javax.swing.JLabel();
        jLabelApellidos = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        jLabelNombres = new javax.swing.JLabel();
        jLabelDireccion = new javax.swing.JLabel();
        jTxtId = new javax.swing.JTextField();
        jTxtApellidos = new javax.swing.JTextField();
        jTxtTelefono = new javax.swing.JTextField();
        jTxtNombres = new javax.swing.JTextField();
        jTxtDireccion = new javax.swing.JTextField();
        jAlergias = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        comboAlergias = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        listAlergias = new javax.swing.JList<>();
        jControles = new javax.swing.JPanel();
        btnActualizar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnVerificar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 970, 555));
        setLocation(new java.awt.Point(0, 0));
        setPreferredSize(new java.awt.Dimension(980, 600));
        setSize(new java.awt.Dimension(970, 555));
        getContentPane().setLayout(null);

        jContenido.setMinimumSize(new java.awt.Dimension(970, 555));
        jContenido.setPreferredSize(new java.awt.Dimension(980, 600));
        jContenido.setLayout(null);

        jDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "-- [ Datos Personales ] --", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(0, 51, 255))); // NOI18N

        jLabelId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelId.setText("Identificación");

        jLabelApellidos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelApellidos.setText("Apellidos");

        jLabelTelefono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelTelefono.setText("Télefono");

        jLabelNombres.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNombres.setText("Nombres");

        jLabelDireccion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelDireccion.setText("Dirección");

        jTxtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDatosLayout = new javax.swing.GroupLayout(jDatos);
        jDatos.setLayout(jDatosLayout);
        jDatosLayout.setHorizontalGroup(
            jDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDatosLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelId)
                    .addGroup(jDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelTelefono)
                        .addComponent(jLabelApellidos)))
                .addGap(18, 18, 18)
                .addGroup(jDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDatosLayout.createSequentialGroup()
                        .addGroup(jDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtId, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addGroup(jDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDireccion)
                            .addComponent(jLabelNombres)))
                    .addComponent(jTxtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTxtNombres)
                    .addComponent(jTxtDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jDatosLayout.setVerticalGroup(
            jDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDatosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelId)
                    .addComponent(jTxtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelApellidos)
                    .addComponent(jTxtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombres)
                    .addComponent(jTxtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelefono)
                    .addComponent(jTxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDireccion)
                    .addComponent(jTxtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        jContenido.add(jDatos);
        jDatos.setBounds(19, 19, 931, 193);

        jAlergias.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "--[ Alergias ] --", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(0, 51, 255))); // NOI18N

        btnAgregar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAgregar.setText("Agregar");

        jScrollPane1.setViewportView(listAlergias);

        javax.swing.GroupLayout jAlergiasLayout = new javax.swing.GroupLayout(jAlergias);
        jAlergias.setLayout(jAlergiasLayout);
        jAlergiasLayout.setHorizontalGroup(
            jAlergiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAlergiasLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jAlergiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jAlergiasLayout.createSequentialGroup()
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboAlergias, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jAlergiasLayout.setVerticalGroup(
            jAlergiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAlergiasLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jAlergiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(comboAlergias, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addGap(14, 14, 14))
        );

        jContenido.add(jAlergias);
        jAlergias.setBounds(19, 230, 585, 309);

        jControles.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "-- [ Controles ] --", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(0, 51, 255))); // NOI18N

        btnActualizar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnActualizar.setText("Actualizar");

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");

        btnVerificar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVerificar.setText("Verificar");

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGuardar.setText("Guardar Datos");

        javax.swing.GroupLayout jControlesLayout = new javax.swing.GroupLayout(jControles);
        jControles.setLayout(jControlesLayout);
        jControlesLayout.setHorizontalGroup(
            jControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jControlesLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jControlesLayout.createSequentialGroup()
                        .addComponent(btnVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jControlesLayout.createSequentialGroup()
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jControlesLayout.setVerticalGroup(
            jControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jControlesLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jContenido.add(jControles);
        jControles.setBounds(622, 230, 328, 309);

        getContentPane().add(jContenido);
        jContenido.setBounds(0, 0, 980, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnActualizar() {
        return btnActualizar;
    }

    public void setBtnActualizar(JButton btnActualizar) {
        this.btnActualizar = btnActualizar;
    }

    public JButton getBtnAgregar() {
        return btnAgregar;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }
    
    public JButton getBtnVerificar() {
        return btnVerificar;
    }
    
    public JButton getBtnGuardar() {
        return btnGuardar;
    }

    public JComboBox<String> getComboAlergias() {
        return comboAlergias;
    }

    public void setComboAlergias(JComboBox<String> cboxAlergias) {
        this.comboAlergias = cboxAlergias;
    }

    public String getjTxtApellidos() {
        return jTxtApellidos.getText();
    }

    public String getjTxtDireccion() {
        return jTxtDireccion.getText();
    }

    public String getjTxtNombres() {
        return jTxtNombres.getText();
    }

    public String getjTxtTelefono() {
        return jTxtTelefono.getText();
    }

    public void setjTxtApellidos(String jTxtApellidos) {
        this.jTxtApellidos.setText(jTxtApellidos);
    }

    public void setjTxtDireccion(String jTxtDireccion) {
        this.jTxtDireccion.setText(jTxtDireccion);
    }

    public Integer getjTxtId() {
        if(jTxtId.getText().isEmpty()){
            return -1;
        }
        return Integer.parseInt(jTxtId.getText());
    }

    public void setjTxtId(String jTxtId) {
        this.jTxtId.setText(jTxtId);
    }

    public void setjTxtNombres(String jTxtNombres) {
        this.jTxtNombres.setText(jTxtNombres);
    }

    public void setjTxtTelefono(String jTxtTelefono) {
        this.jTxtTelefono.setText(jTxtTelefono);
    }

    public JList<String> getListAlergias() {
        return listAlergias;
    }

    public void setListAlergias(DefaultListModel model) {
        this.listAlergias.setModel(model);
    }
    
    public void addBtnAgregar(ActionListener listener){
        btnAgregar.addActionListener(listener);
    }
    
    public void addBtnActualizar(ActionListener listener){
        btnActualizar.addActionListener(listener);
    }
    
    public void addBtnCancelar(ActionListener listener){
        btnCancelar.addActionListener(listener);
    }
    
    public void addBtnVerificar(ActionListener listener){
        btnVerificar.addActionListener(listener);
    }
    
    public void addBtnGuardar(ActionListener listener){
        btnGuardar.addActionListener(listener);
    }
    
    public void addComboAlergias(ActionListener listener){
        comboAlergias.addActionListener(listener);
    }
    
    private void jTxtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnVerificar;
    private javax.swing.JComboBox<String> comboAlergias;
    private javax.swing.JPanel jAlergias;
    private javax.swing.JPanel jContenido;
    private javax.swing.JPanel jControles;
    private javax.swing.JPanel jDatos;
    private javax.swing.JLabel jLabelApellidos;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelNombres;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxtApellidos;
    private javax.swing.JTextField jTxtDireccion;
    private javax.swing.JTextField jTxtId;
    private javax.swing.JTextField jTxtNombres;
    private javax.swing.JTextField jTxtTelefono;
    private javax.swing.JList<String> listAlergias;
    // End of variables declaration//GEN-END:variables
}
